/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intvector {
	int n;
	struct {
		u_int vector_len;
		int *vector_val;
	} vector;
};
typedef struct intvector intvector;

struct intpair {
	int min;
	int max;
};
typedef struct intpair intpair;

struct product {
	float a;
	intvector vector;
};
typedef struct product product;

struct floatvector {
	int n;
	struct {
		u_int elements_len;
		float *elements_val;
	} elements;
};
typedef struct floatvector floatvector;

#define INTERFACE_PROG 0x23451111
#define INTERFACE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define calculate_average 1
extern  float * calculate_average_1(intvector *, CLIENT *);
extern  float * calculate_average_1_svc(intvector *, struct svc_req *);
#define find_max_min 2
extern  intpair * find_max_min_1(intvector *, CLIENT *);
extern  intpair * find_max_min_1_svc(intvector *, struct svc_req *);
#define multiply_scalar 3
extern  floatvector * multiply_scalar_1(product *, CLIENT *);
extern  floatvector * multiply_scalar_1_svc(product *, struct svc_req *);
extern int interface_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calculate_average 1
extern  float * calculate_average_1();
extern  float * calculate_average_1_svc();
#define find_max_min 2
extern  intpair * find_max_min_1();
extern  intpair * find_max_min_1_svc();
#define multiply_scalar 3
extern  floatvector * multiply_scalar_1();
extern  floatvector * multiply_scalar_1_svc();
extern int interface_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intvector (XDR *, intvector*);
extern  bool_t xdr_intpair (XDR *, intpair*);
extern  bool_t xdr_product (XDR *, product*);
extern  bool_t xdr_floatvector (XDR *, floatvector*);

#else /* K&R C */
extern bool_t xdr_intvector ();
extern bool_t xdr_intpair ();
extern bool_t xdr_product ();
extern bool_t xdr_floatvector ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
