/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "idl.h"

bool_t
xdr_intvector (XDR *xdrs, intvector *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->vector.vector_val, (u_int *) &objp->vector.vector_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_intpair (XDR *xdrs, intpair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_product (XDR *xdrs, product *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_intvector (xdrs, &objp->vector))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_floatvector (XDR *xdrs, floatvector *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->elements.elements_val, (u_int *) &objp->elements.elements_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
