SELECT *
FROM EMP;

SELECT EMPNO,ENAME,JOB,SAL,COMM,SAL+COMM,SAL+IFNULL(COMM,0)
FROM EMP;

SELECT ENAME,JOB,SAL
FROM EMP
ORDER BY SAL DESC;

SELECT EMPNO,ENAME,JOB,SAL
FROM EMP
WHERE JOB='ANALYST' OR JOB='SALESMAN' AND SAL>1000;

SELECT MAX(SAL) AS 'MAX(SAL)',MIN(SAL) AS 'MIN(SAL)',AVG(SAL) AS 'AVG(SAL)'
FROM EMP;

SELECT ENAME,LOWER(ENAME),SUBSTR(ENAME,1,3)
FROM EMP;

SELECT COUNT(*)
FROM DEPT,EMP;

SELECT EMPNO,ENAME,IFNULL(EMP.DEPTNO,0),DNAME
FROM DEPT,EMP;

SELECT *
FROM DEPT,EMP
WHERE DEPT.DEPTNO=EMP.DEPTNO;

SET AUTOCOMMIT=0;
UPDATE EMP
SET SAL=SAL*1.10;

ROLLBACK;

SELECT *
FROM EMP;

SET AUTOCOMMIT=0;
SELECT  * FROM EMP;
DELETE FROM EMP WHERE EMPNO=7369;

ROLLBACK;

SELECT *FROM EMP;

SELECT DISTINCT job
FROM EMP
ORDER BY job;

SELECT empno, ename, job, sal 
FROM EMP
WHERE (job IN ("ANALYST", "PROGRAMMER"))
AND (sal>= 1300 OR sal+IFNULL(comm,0)>= 1800)
ORDER BY job, ename, sal;

SELECT empno, ename, job, sal 
FROM EMP
WHERE job IN ("ANALYST", "PROGRAMMER")
AND ename LIKE "%ES"
AND sal BETWEEN 1000 AND 7000;


SELECT empno, ename, job, sal, deptno 
FROM EMP
WHERE sal > (SELECT MIN(sal)
             FROM EMP
             WHERE deptno IN (10, 20))            
ORDER BY deptno, ename;





