DESCRIBE DEPT;
DESCRIBE EMP;

SELECT *
FROM DEPT,EMP;

SELECT * 
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT ENAME,SAL,LOC 
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND JOB='SALESMAN';

SELECT ENAME, JOB, SAL, LOC
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = 'SALESMAN';

SELECT ENAME,SAL
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND DEPT.LOC='DALLAS' AND EMP.JOB='CLERK';